version: '3.5'
services:
  app:
    container_name: docker-youtube-idea
    restart: always
    build: .
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./dbdata:/usr/src/app/dbdata 
    depends_on:
      - mongo
    networks:
      - node-network
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
    networks:
      - node-network
  nginx:
    container_name: youtube-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    networks:
      - node-network
    ports:
      - '80:80'

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
    