version: '3.5'
services:
  app:
    container_name: docker-youtube-idea
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    ports:
      - '27017:27017'

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

    ports:
      - '80:80'

volumes:
  mongo_data:
    external: true


    